### ISSUE TITLE
Inconsisient error happens in autotuning

### ISSUE THREAD

**Issue by seongwook-ham** [facebookresearch/TensorComprehensions#207]
`import tensor_comprehensions as tc

import math as ma
import torch
import torch.nn as nn
import torch.nn.functional as F
import random
import time
import os

from torch.autograd import Function

LANG = """
def function(float(N,C,H,W) I, float(C) S, int32(L,A) R, int32(C) R2) -> (output){
output(n,l,h,w) +=! (R(l,a)==C? float(0):I(n,R(l,a),h,w) * S(R(l,a)))
}
def function_grad(float(N,C,H,W) I, float(C) S, int32(L,A) R, int32(C) R2, float(N,L,H,W) output_grad) -> (I_grad, S_grad, R_grad, R2_grad){
I_grad(n,c,h,w) = S(c) * output_grad(n,R2(c),h,w)  where c in 0:C
S_grad(kk) +=! I(n,kk,h,w) * output_grad(n,R2(kk),h,w)  where kk in 0:C
R_grad(l,a) = 0 where l in 0:L, a in 0:A
R2_grad(k) = 0 where k in 0:C
}
"""

batch=32
width=height=32
generations=35

L=92
A=9

C = 656

    
    

for i in range(20):
    mat1 = torch.ones(batch, C, width, height).cuda()
    mat2 = torch.ones(C).cuda()
    
    
    mat3 = torch.ones(L,A).int().random_(0,C+100).clamp_(0, C)
    
    mat3=mat3.cuda()
    
    
    
    
    mat4 = torch.ones(C).int().random_(0,L).cuda()
    
    
    mat1 = torch.autograd.Variable(mat1, requires_grad =True)
    mat2= torch.autograd.Variable(mat2, requires_grad =True)
    mat3= torch.autograd.Variable(mat3)
    mat4= torch.autograd.Variable(mat4)
    
    autograd = tc.define(LANG, training=True, name="function", backward="function_grad")
    
    autograd.autotune(mat1, mat2, mat3, mat4, options=[tc.Options("mlp"), tc.Options("mlp")], cache="temp.tc", pop_size=100, generations=generations, gpus="0,1,2,3", threads=15)

    del mat1,mat2,mat3,mat4
        
    torch.cuda.empty_cache()`

with code above, when i use autotuner for funcion, inconsisient error happens. but when i call function it acts normally.
for example autotuner  act normally in forward generation 1-35 and backward generation 1-19, but in backward generation 20, error occurs.
here is error message

[error.txt](https://github.com/facebookresearch/TensorComprehensions/files/1844620/error.txt)

why this inconsistent occurs? and how could i solve it?

**Comment by prigoyal** [comment]
Hi @seongwook-ham , have you tried re-running the autotuning? If not, can you re-try and report if you still get the error? thanks

**Comment by ftynse** [comment]
> why this intermittent error occurs? 

On each run, the autotuner may check different mapping options.  The error occurs with at least one configuration of options, or maybe a certain set.  It may or may not appear on the subsequent run.

@prigoyal autotuner runs are inherently non-deterministic.  They may uncover some errors in one run, and then complete just fine for a long time.

> and how could i solve it?

Thanks for reporting it, we will take a look.  From the error report, it looks like a memory corruption, so unfortunately I don't have a quick workaround for you.

**Comment by ftynse** [comment]
> indent is not properly expressed in github

It is if you wrap your code into three backticks (or use the "<>" button in the interface).

**Comment by seongwook-ham** [comment]
it do not work for elementwise. and works for other option but makes error intermittently.
this error occurs about once every 1-4 hours. so i re-run the script when occurs error.

**Comment by nicolasvasilache** [comment]
Errors and corresponding options should get automatically logged to
/tmp/xxx.WARNING and /tmp/xxx.ERROR could you please paste say the last 100
lines of those files in a gist?
Thanks!

**Comment by ftynse** [comment]
> t do not work for elementwise.

The options you pass to the autotuner are only a _starting point_ for the search.  In each run, the autotuner picks thousands of random options combinations.

**Comment by seongwook-ham** [comment]
i run script on aws one more time and following error occurs intermittently. 
Check failed: !subscriptAff.get() expected one piece
*** Check failure stack trace: ***
Aborted (core dumped)
but /tmp/xxx.WARNING and /tmp/xxx.ERROR does not exist in aws ec2

**Comment by ftynse** [comment]
> Check failed: !subscriptAff.get() expected one piece

I might have identified it in #200 and fix is available in #202.  If this is the only error that appears for you, let's close this issue as a duplicat.

> but /tmp/xxx.WARNING and /tmp/xxx.ERROR does not exist in aws ec2

It's not literally `xxx`, anything with `.WARNING` or `.ERROR` extensions.

**Comment by nicolasvasilache** [comment]
> It's not literally xxx, anything with .WARNING or .ERROR extensions.

@seongwook-ham indeed, in C++ it is your binary name followed by ```.WARNING``` or ```.ERROR``` extensions. Not sure what that looks like from python atm.

**Comment by seongwook-ham** [comment]
i think aws do not makes log. i use ls -a in tmp folder no file is found.
as i already update to master branch and rebuild tc (after commit 7b291e3 is merged into master)
it still throw error.

    .tile(164)
    .mapToThreads(6, 82)
    .mapToBlocks(32, 64)
    .unroll(128)
    .tileImperfectlyNested(false)
    .useSharedMemory(true)
    .usePrivateMemory(false)
    .unrollCopyShared(false)
    .matchLibraryCalls(true);
F0326 19:04:45.027912 21383 genetic_tuning_harness.cc:437] [CUDA][FATAL] cuda error on gpu 7: Error at: /home/ubuntu/TensorComprehensions/src/autotuner/genetic_tuning_harness.cc:435: an illegal memory access was encountered
tc::MappingOptions::makeNaiveMappingOptions()
    .outerScheduleFusionStrategy(tc::FusionStrategy::Min)
    .outerScheduleAllowSkewing(false)
    .outerSchedulePositiveOrthant(true)
    .intraTileScheduleFusionStrategy(tc::FusionStrategy::Min)
    .intraTileScheduleAllowSkewing(false)
    .intraTileSchedulePositiveOrthant(true)
    .tile(21, 2, 328, 21)
    .mapToThreads(164)
    .mapToBlocks(3)
    .unroll(8)
    .tileImperfectlyNested(false)
    .useSharedMemory(true)
    .usePrivateMemory(false)
    .unrollCopyShared(true)
    .matchLibraryCalls(false);
F0326 19:04:45.027978 21381 genetic_tuning_harness.cc:437] [CUDA][FATAL] cuda error on gpu 5: Error at: /home/ubuntu/TensorComprehensions/src/autotuner/genetic_tuning_harness.cc:435: an illegal memory access was encountered
tc::MappingOptions::makeNaiveMappingOptions()
    .outerScheduleFusionStrategy(tc::FusionStrategy::Preserve3Coincident)
    .outerScheduleAllowSkewing(false)
    .outerSchedulePositiveOrthant(true)
    .intraTileScheduleFusionStrategy(tc::FusionStrategy::Max)
    .intraTileScheduleAllowSkewing(false)
    .intraTileSchedulePositiveOrthant(true)
    .tile(23, 256)
    .mapToThreads(2, 64)
    .mapToBlocks(92)
    .unroll(4)
    .tileImperfectlyNested(false)
    .useSharedMemory(false)
    .usePrivateMemory(false)
    .unrollCopyShared(true)
    .matchLibraryCalls(true);
Aborted (core dumped)

am i right to use git clean -f -d in side https://facebookresearch.github.io/TensorComprehensions/installation_conda.html 7?
except that i exactly followed 6 and 7

**Comment by seongwook-ham** [comment]
i update to master branch and rebuild tc (after commit  c315745  is merged into master) and re-run the code one more time.
    .useSharedMemory(false)
    .usePrivateMemory(false)
    .unrollCopyShared(true)
    .matchLibraryCalls(false);
*** Check failure stack trace: ***
W0327 00:42:49.319322  9061 genetic_tuning_harness.cc:435] Error at: /home/ubuntu/TensorComprehensions/src/autotuner/genetic_tuning_harness.cc:435: an illegal memory access was encountered
F0327 00:42:49.319197  9064 genetic_tuning_harness.cc:437] [CUDA][FATAL] cuda error on gpu 7: Error at: /home/ubuntu/TensorComprehensions/src/autotuner/genetic_tuning_harness.cc:435: an illegal memory access was encountered
tc::MappingOptions::makeNaiveMappingOptions()
    .outerScheduleFusionStrategy(tc::FusionStrategy::Preserve3Coincident)
    .outerScheduleAllowSkewing(false)
    .outerSchedulePositiveOrthant(true)F0327 00:42
4  3.intraTileScheduleFusionStrategy( c::FusionStrategy::Min) 9058 genetic_tuning_harness.cc
4   [CUDA][FATAL] cuda error on gpu intraTileScheduleAllowSkewing(: lse)Error at: /home/ubuntu/TensorComprehensions/src/autotuner/genetic_tuning_harness.cc:435: an illegal memory access was encountered

   t.intraTileSchedulePositiveOrthant(true)
    .tile(512)

mapToThreads(92)    .outerScheduleFusionStrategy(tc::FusionStrategy::Preserve3Coincident)
    .mapToBlocks(5    82.outerScheduleAllowSkewing
    .
   2.(true)
    .tileImperfectlyNested(false)
    .useSharedMemory(false)

 .   .intraTileScheduleFusionStrategy(tc::FusionStrategy::Max
    .unrollCopyShared(
 lse)
    .matchLibraryCalls(true)ewing(false);

    .intraTileSchedulePositiveOrthant(true)
    .tile(256, 5, 3)
    .mapToThreads(32)
    .mapToBlocks(1)
    .unroll(16)
    .tileImperfectlyNested(false)
    .useSharedMemory(false)
    .usePrivateMemory(false)
    .unrollCopyShared(true)
    .matchLibraryCalls(false);
W0327 00:42:49.319356  9060 genetic_tuning_harness.cc:435] Error at: /home/ubuntu/TensorComprehensions/src/autotuner/genetic_tuning_harness.cc:435: an illegal memory access was encountered
*** Check failure stack trace: ***
Aborted (core dumped)

**Comment by prigoyal** [comment]
thanks @seongwook-ham for your efforts in getting the options. This feels like we have a stable repro for intermittent issue that we have been trying to figure out for some time. @nicolasvasilache , @ftynse what do you guys recommend as the next steps? the mapping options are also available now :)

**Comment by prigoyal** [comment]
assigned tentatively to @ftynse / @nicolasvasilache to help investigate the options or point in the right direction :)

**Comment by seongwook-ham** [comment]
is there some progress? @ftynse @nicolasvasilache

**Comment by skimo-openhub** [comment]
On Mon, Mar 26, 2018 at 06:13:01PM -0700, Priya Goyal wrote:
> thanks @seongwook-ham for your efforts in getting the options. This feels like we have a stable repro for intermittent issue that we have been trying to figure out for some time. @nicolasvasilache , @ftynse what do you guys recommend as the next steps? the mapping options are also available now :) 

Could you construct a C++ reproducer?

skimo

**Comment by ftynse** [comment]
> `mat3 = torch.ones(L,A).int().random_(0,C+100).clamp_(0, C)`

I think `clamp` _includes_ the right bound (see [here](http://pytorch.org/docs/master/torch.html#torch.clamp)), so your code might be reading from the incorrect address in `S(R(l,a)))` depending on which random numbers get generated.  `S(C-1)` is the last element you can legitimately access.

**Comment by seongwook-ham** [comment]
output(n,l,h,w) +=! (R(l,a)==C? float(0):I(n,R(l,a),h,w) * S(R(l,a)))
when R(l,a)==C we do not access S(C). instead use 0.
it acts well in forward path.
there is problem is back propagation pass intermittently

**Comment by seongwook-ham** [comment]
expected ident but found 'min' here: when i use min(R(l,a),C-1) instead of R(l,a)

**Comment by seongwook-ham** [comment]
@skimo-openhub what does  C++ reproducer means?

**Comment by seongwook-ham** [comment]
if you want to know function without autotuning act normally run following code
```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Mar 23 21:33:30 2018

@author: hswserverubuntu
"""

import tensor_comprehensions as tc


import math as ma
import torch
import torch.nn as nn
import torch.nn.functional as F
import random
import time
import os

from torch.autograd import Function

LANG = """
def function(float(N,C,H,W) I, float(C) S, int32(L,A) R, int32(C) R2) -> (output){
output(n,l,h,w) +=! (R(l,a)==C? float(0):I(n,R(l,a),h,w) * S(R(l,a)))
}
def function_grad(float(N,C,H,W) I, float(C) S, int32(L,A) R, int32(C) R2, float(N,L,H,W) output_grad) -> (I_grad, S_grad, R_grad, R2_grad){
I_grad(n,c,h,w) = S(c) * output_grad(n,R2(c),h,w)  where c in 0:C
S_grad(kk) +=! I(n,kk,h,w) * output_grad(n,R2(kk),h,w)  where kk in 0:C
R_grad(l,a) = 0 where l in 0:L, a in 0:A
R2_grad(k) = 0 where k in 0:C
}
"""
LANG2 = """
def function(float(N,C,H,W) I, float(C) S, int32(L,A) R, int32(C) R2) -> (output){
output(n,l,h,w) +=! (R(l,a)==C? float(0):I(n,R(l,a),h,w) * S(R(l,a)))
}
def function_grad(float(N,C,H,W) I, float(C) S, int32(L,A) R, int32(C) R2, float(N,L,H,W) output_grad) -> (I_grad, S_grad, R_grad, R2_grad){
I_grad(n,c,h,w) = S(c) * output_grad(n,R2(c),h,w)  where c in 0:C
S_grad(c) +=! I(n,c,h,w) * output_grad(n,R2(c),h,w)  where c in 0:C
R_grad(l,a) = 0 where l in 0:L, a in 0:A
R2_grad(c) = 0 where c in 0:C
}
"""

LANG3 = """
def function(float(N,C,H,W) I, float(C) S, int32(L,A) R, int32(C) R2) -> (output){
output(n,l,h,w) +=! (R(l,a)==C? float(0):I(n,R(l,a),h,w) * S(R(l,a)))
}
def function_grad(float(N,C,H,W) I, float(C) S, int32(L,A) R, int32(C) R2, float(N,L,H,W) output_grad) -> (I_grad, S_grad, R_grad, R2_grad){
I_grad(n,c,h,w) = S(c) * output_grad(n,R2(c),h,w)  where c in 0:C
S_grad(c) +=! I(n,c,h,w) * output_grad(n,R2(c),h,w)  where c in 0:C
R_grad(l,a) = 0 where exists R(l,a)
R2_grad(c) = 0 where exists R2(c)
}
"""




used_lang=LANG2


batch=32
width=height=32
generations=1

L=92
A=9

C = 656




    
    


'''
for i in range(50):
    mat1 = torch.ones(batch, C, width, height).cuda()
    mat2 = torch.ones(C).cuda()
    
    
    mat3 = torch.ones(L,A).int().random_(0,C+100).clamp_(0, C)
    
    mat3=mat3.cuda()
    
    
    
    
    mat4 = torch.ones(C).int().random_(0,L).cuda()
    
    
    mat1 = torch.autograd.Variable(mat1, requires_grad =True)
    mat2= torch.autograd.Variable(mat2, requires_grad =True)
    mat3= torch.autograd.Variable(mat3)
    mat4= torch.autograd.Variable(mat4)
    
    autograd = tc.define(used_lang, training=True, name="function", backward="function_grad")
    
    autograd.autotune(mat1, mat2, mat3, mat4, options=[tc.Options("mlp"), tc.Options("mlp")], cache="temp.tc", pop_size=100, generations=generations, gpus="0,1,2,3,4,5,6,7", threads=23)

    del mat1,mat2,mat3,mat4
        
    torch.cuda.empty_cache()
'''
for i in range(50):
    mat1 = torch.ones(batch, C, width, height).cuda()
    mat2 = torch.ones(C).cuda()
    
    
    mat3 = torch.ones(L,A).int().random_(0,C+100).clamp_(0, C)
    
    mat3=mat3.cuda()
    
    
    
    
    mat4 = torch.ones(C).int().random_(0,L).cuda()
    
    
    mat1 = torch.autograd.Variable(mat1, requires_grad =True)
    mat2= torch.autograd.Variable(mat2, requires_grad =True)
    mat3= torch.autograd.Variable(mat3, requires_grad =True)
    mat4= torch.autograd.Variable(mat4, requires_grad =True)
    
    autograd = tc.define(used_lang, training=True, name="function", backward="function_grad")
    
    out=autograd(mat1, mat2, mat3, mat4)
    out.sum().backward()
    
    #print(out)
    print(out[0,:,0,0])
    #print(mat1.grad)
    #print(mat1.grad[0,:,0,0])
    #print(mat2.grad)
    #print(mat3.grad)
    #print(mat4.grad)
	
    del mat1,mat2,mat3,mat4,out
        
    torch.cuda.empty_cache()
    time.sleep(-1)
```

**Comment by seongwook-ham** [comment]
@prigoyal @ftynse @nicolasvasilache 
i got some weird phenomenon.
when i replace form of 'where x in 0:X' with 'where exists D(x)'. error occur less frequently.
following code is example. if i use 'used_lang=LANG' error occurs very frequently. but when i use 'used_lang=LAN4' error occurs not that frequently

```python
import tensor_comprehensions as tc


import math as ma
import torch
import torch.nn as nn
import torch.nn.functional as F
import random
import time
import os

from torch.autograd import Function

LANG = """
def function(float(N,C,H,W) I, float(C) S, int32(L,A) R, int32(C) R2) -> (output){
output(n,l,h,w) +=! (R(l,a)==C? float(0):I(n,R(l,a),h,w) * S(R(l,a)))
}
def function_grad(float(N,C,H,W) I, float(C) S, int32(L,A) R, int32(C) R2, float(N,L,H,W) output_grad) -> (I_grad, S_grad, R_grad, R2_grad){
I_grad(n,c,h,w) = S(c) * output_grad(n,R2(c),h,w)  where c in 0:C
S_grad(kk) +=! I(n,kk,h,w) * output_grad(n,R2(kk),h,w)  where kk in 0:C
R_grad(l,a) = 0 where l in 0:L, a in 0:A
R2_grad(k) = 0 where k in 0:C
}
"""

LANG2 = """
def function(float(N,C,H,W) I, float(C) S, int32(L,A) R, int32(C) R2) -> (output){
output(n,l,h,w) +=! (R(l,a)==C? float(0):I(n,R(l,a),h,w) * S(R(l,a)))
}
def function_grad(float(N,C,H,W) I, float(C) S, int32(L,A) R, int32(C) R2, float(N,L,H,W) output_grad) -> (I_grad, S_grad, R_grad, R2_grad){
I_grad(n,c,h,w) = S(c) * output_grad(n,R2(c),h,w)  where c in 0:C
S_grad(c) +=! I(n,c,h,w) * output_grad(n,R2(c),h,w)  where c in 0:C
R_grad(l,a) = 0 where l in 0:L, a in 0:A
R2_grad(c) = 0 where c in 0:C
}
"""


LANG3 = """
def function(float(N,C,H,W) I, float(C) S, int32(L,A) R, int32(C) R2) -> (output){
output(n,l,h,w) +=! (R(l,a)==C? float(0):I(n,R(l,a),h,w) * S(R(l,a)))
}
def function_grad(float(N,C,H,W) I, float(C) S, int32(L,A) R, int32(C) R2, float(N,L,H,W) output_grad) -> (I_grad, S_grad, R_grad, R2_grad){
I_grad(n,c,h,w) = S(c) * output_grad(n,R2(c),h,w)  where exists R2(c)
S_grad(c) +=! I(n,c,h,w) * output_grad(n,R2(c),h,w)  where exists R2(c)
R_grad(l,a) = 0 where exists R(l,a)
R2_grad(c) = 0 where exists R2(c)
}
"""

LANG4 = """
def function(float(N,C,H,W) I, float(C) S, int32(L,A) R, int32(C) R2) -> (output){
output(n,l,h,w) +=! (R(l,a)==C? float(0):I(n,R(l,a),h,w) * S(R(l,a)))
}
def function_grad(float(N,C,H,W) I, float(C) S, int32(L,A) R, int32(C) R2, float(N,L,H,W) output_grad) -> (I_grad, S_grad, R_grad, R2_grad){
I_grad(n,c,h,w) = S(c) * output_grad(n,R2(c),h,w) where exists R2(c)
S_grad(kk) +=! I(n,kk,h,w) * output_grad(n,R2(kk),h,w) where exists R2(kk)
R_grad(l,a) = 0 where exists R(l,a)
R2_grad(k) = 0 where R2(k)
}
"""




used_lang=LANG4


batch=32
width=height=32
generations=1

L=92
A=9

C = 656




    
    



for i in range(50):
    mat1 = torch.ones(batch, C, width, height).cuda()
    mat2 = torch.ones(C).cuda()
    
    
    mat3 = torch.ones(L,A).int().random_(0,C+100).clamp_(0, C)
    
    mat3=mat3.cuda()
    
    
    
    
    mat4 = torch.ones(C).int().random_(0,L).cuda()
    
    
    mat1 = torch.autograd.Variable(mat1, requires_grad =True)
    mat2= torch.autograd.Variable(mat2, requires_grad =True)
    mat3= torch.autograd.Variable(mat3, requires_grad =True)
    mat4= torch.autograd.Variable(mat4, requires_grad =True)
    
    autograd = tc.define(used_lang, training=True, name="function", backward="function_grad")
    
    autograd.autotune(mat1, mat2, mat3, mat4, options=[tc.Options("mlp"), tc.Options("mlp")], cache="temp.tc", pop_size=100, generations=generations, gpus="0,1,2,3,4,5,6,7", threads=32)

    del mat1,mat2,mat3,mat4
        
    torch.cuda.empty_cache()
```

**Comment by skimo-openhub** [comment]
On Fri, Mar 30, 2018 at 08:41:02PM -0700, Roadwalker wrote:
> @skimo-openhub what does  C++ reproducer means?

A reproducer in C++.  That is, code that uses the C++ interface
rather than the Python interface and that exhibits the same
problematic behavior.

skimo

**Comment by ftynse** [comment]
@prigoyal could you please convert this code into a C++ test?  We are particularly interested in a standalone call to the backward function. Thanks.

**Comment by prigoyal** [comment]
@skimo-openhub , @ftynse , here is the PR with the C++ test https://github.com/facebookresearch/TensorComprehensions/pull/285 for the backwards layer.

**Comment by seongwook-ham** [comment]
Generation 2	Jobs(Compiled, GPU)/total  (74, 54)/100   (best/median/worst)us: 23897/36399/109224*** Error in `python': free(): invalid next size (normal): 0x00007f9ccc716dd0 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f9dcd9e67e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7f9dcd9ef37a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f9dcd9f353c]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(isl_basic_map_add_constraints_dim_map+0x196)[0x7f9d8e61443f]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(isl_basic_map_insert_dims+0x223)[0x7f9d8e647d29]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(isl_basic_map_add_dims+0x49)[0x7f9d8e647db0]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(isl_basic_set_add_dims+0x78)[0x7f9d8e647e2a]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(isl_basic_map_gist+0x16a)[0x7f9d8e66a4fe]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(isl_basic_set_gist+0x37)[0x7f9d8e66b379]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(isl_ast_build_compute_gist_basic_set+0x67)[0x7f9d8e5e1fc5]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(+0xad760)[0x7f9d8e5f0760]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(+0xadcba)[0x7f9d8e5f0cba]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(+0xae1b5)[0x7f9d8e5f11b5]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(+0xae8ac)[0x7f9d8e5f18ac]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(+0xaeb2a)[0x7f9d8e5f1b2a]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(+0xb0895)[0x7f9d8e5f3895]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(+0xb0e04)[0x7f9d8e5f3e04]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(+0xb11cc)[0x7f9d8e5f41cc]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(+0xb2f00)[0x7f9d8e5f5f00]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(+0xb36bc)[0x7f9d8e5f66bc]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(+0xb4407)[0x7f9d8e5f7407]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(+0xb4597)[0x7f9d8e5f7597]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(+0xabc2a)[0x7f9d8e5eec2a]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(+0xb2eda)[0x7f9d8e5f5eda]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(+0xad815)[0x7f9d8e5f0815]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(+0xadcba)[0x7f9d8e5f0cba]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(+0xae1b5)[0x7f9d8e5f11b5]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(+0xae5aa)[0x7f9d8e5f15aa]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(+0x186a97)[0x7f9d8e6c9a97]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(isl_basic_set_list_foreach_scc+0x1c8)[0x7f9d8e6c9c61]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(+0xae8f2)[0x7f9d8e5f18f2]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(+0xaea17)[0x7f9d8e5f1a17]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(isl_basic_set_list_foreach_scc+0x191)[0x7f9d8e6c9c2a]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(+0xaeb82)[0x7f9d8e5f1b82]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(+0xb0895)[0x7f9d8e5f3895]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(+0xb0e04)[0x7f9d8e5f3e04]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(+0xb11cc)[0x7f9d8e5f41cc]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(+0xb2f00)[0x7f9d8e5f5f00]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(+0xb36bc)[0x7f9d8e5f66bc]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(+0xb4407)[0x7f9d8e5f7407]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(+0xb4597)[0x7f9d8e5f7597]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(+0xabc2a)[0x7f9d8e5eec2a]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(+0xb2eda)[0x7f9d8e5f5eda]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(+0xad815)[0x7f9d8e5f0815]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(+0xadf6b)[0x7f9d8e5f0f6b]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(+0xae1b5)[0x7f9d8e5f11b5]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(+0xae8ac)[0x7f9d8e5f18ac]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(+0xaeb2a)[0x7f9d8e5f1b2a]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(+0xb0895)[0x7f9d8e5f3895]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(+0xb0e04)[0x7f9d8e5f3e04]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(+0xb11cc)[0x7f9d8e5f41cc]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(+0xb2f00)[0x7f9d8e5f5f00]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(+0xb36bc)[0x7f9d8e5f66bc]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(+0xb4407)[0x7f9d8e5f7407]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(+0xb4597)[0x7f9d8e5f7597]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(+0xb3d86)[0x7f9d8e5f6d86]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(+0xb44a9)[0x7f9d8e5f74a9]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(+0xb4597)[0x7f9d8e5f7597]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(+0xb3d86)[0x7f9d8e5f6d86]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(+0xb44a9)[0x7f9d8e5f74a9]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(+0xb4597)[0x7f9d8e5f7597]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(+0xb3d86)[0x7f9d8e5f6d86]
/home/hswserverubuntu/TensorComprehensions/third-party-install/lib/libisl.so(+0xb44a9)[0x7f9d8e5f74a9]
======= Memory map: ========
200000000-200200000 rw-s 00000000 00:06 463                              /dev/nvidiactl
200200000-200400000 ---p 00000000 00:00 0 
200400000-200404000 rw-s 00000000 00:06 463                              /dev/nvidiactl
200404000-200600000 ---p 00000000 00:00 0 
200600000-200a00000 rw-s 00000000 00:06 463                              /dev/nvidiactl
200a00000-201600000 ---p 00000000 00:00 0 
201600000-201604000 rw-s 00000000 00:06 463                              /dev/nvidiactl
201604000-201800000 ---p 00000000 00:00 0 
201800000-201c00000 rw-s 00000000 00:06 463                              /dev/nvidiactl
201c00000-202800000 ---p 00000000 00:00 0 
202800000-202804000 rw-s 00000000 00:06 463                              /dev/nvidiactl
202804000-202a00000 ---p 00000000 00:00 0 
202a00000-202e00000 rw-s 00000000 00:06 463                              /dev/nvidiactl
202e00000-203a00000 ---p 00000000 00:00 0 
203a00000-203a04000 rw-s 00000000 00:06 463                              /dev/nvidiactl
203a04000-203c00000 ---p 00000000 00:00 0 
203c00000-204000000 rw-s 00000000 00:06 463                              /dev/nvidiactl
204000000-204c00000 ---p 00000000 00:00 0 
204c00000-204c04000 rw-s 00000000 00:06 463                              /dev/nvidiactl
204c04000-204e00000 ---p 00000000 00:00 0 
204e00000-205200000 rw-s 00000000 00:06 463                              /dev/nvidiactl
205200000-205e00000 ---p 00000000 00:00 0 
205e00000-205e04000 rw-s 00000000 00:06 463                              /dev/nvidiactl
205e04000-206000000 ---p 00000000 00:00 0 
206000000-206400000 rw-s 00000000 00:06 463                              /dev/nvidiactl
206400000-207000000 ---p 00000000 00:00 0 
207000000-207004000 rw-s 00000000 00:06 463                              /dev/nvidiactl
207004000-207200000 ---p 00000000 00:00 0 
207200000-207600000 rw-s 00000000 00:06 463                              /dev/nvidiactl
207600000-208200000 ---p 00000000 00:00 0 
208200000-208204000 rw-s 00000000 00:06 463                              /dev/nvidiactl
208204000-208400000 ---p 00000000 00:00 0 
208400000-208800000 rw-s 00000000 00:06 463                              /dev/nvidiactl
208800000-209400000 ---p 00000000 00:00 0 
209400000-209404000 rw-s 00000000 00:06 463                              /dev/nvidiactl
209404000-209600000 ---p 00000000 00:00 0 
209600000-209a00000 rw-s 00000000 00:06 463                              /dev/nvidiactl
209a00000-209a04000 rw-s 00000000 00:06 463                              /dev/nvidiactl
209a04000-209c00000 ---p 00000000 00:00 0 
209c00000-20a000000 rw-s 00000000 00:06 463                              /dev/nvidiactl
20a000000-20a004000 rw-s 00000000 00:06 463                              /dev/nvidiactl
20a004000-20a200000 ---p 00000000 00:00 0 
20a200000-20a600000 rw-s 00000000 00:06 463                              /dev/nvidiactl
20a600000-20a604000 rw-s 00000000 00:06 463                              /dev/nvidiactl
20a604000-20a800000 ---p 00000000 00:00 0 
20a800000-20ac00000 rw-s 00000000 00:06 463                              /dev/nvidiactl
20ac00000-20ac04000 rw-s 00000000 00:06 463                              /dev/nvidiactl
20ac04000-20ae00000 ---p 00000000 00:00 0 
20ae00000-20b200000 rw-s 00000000 00:06 463                              /dev/nvidiactl
20b200000-20b204000 rw-s 00000000 00:06 463                              /dev/nvidiactl
20b204000-20b400000 ---p 00000000 00:00 0 
20b400000-20b800000 rw-s 00000000 00:06 463                              /dev/nvidiactl
20b800000-20b804000 rw-s 00000000 00:06 463                              /dev/nvidiactl
20b804000-20ba00000 ---p 00000000 00:00 0 
20ba00000-20be00000 rw-s 00000000 00:06 463                              /dev/nvidiactl
20be00000-20be04000 rw-s 00000000 00:06 463                              /dev/nvidiactl
20be04000-20c000000 ---p 00000000 00:00 0 
20c000000-20c400000 rw-s 00000000 00:06 463                              /dev/nvidiactl
20c400000-20c600000 ---p 00000000 00:00 0 
20c600000-20c800000 rw-s 00000000 00:06 463                              /dev/nvidiactl
20c800000-20ca00000 rw-s 00000000 00:06 463                              /dev/nvidiactl
20ca00000-20cc00000 rw-s 00000000 00:06 463                              /dev/nvidiactl
20cc00000-20ce00000 ---p 00000000 00:00 0 
20ce00000-20ce04000 rw-s 00000000 00:06 463                              /dev/nvidiactl
20ce04000-20d000000 ---p 00000000 00:00 0 
20d000000-20d400000 rw-s 00000000 00:06 463                              /dev/nvidiactl
20d400000-20e000000 ---p 00000000 00:00 0 
20e000000-20e004000 rw-s 00000000 00:06 463                              /dev/nvidiactl
20e004000-20e200000 ---p 00000000 00:00 0 
20e200000-20e600000 rw-s 00000000 00:06 463                              /dev/nvidiactl
20e600000-20f200000 ---p 00000000 00:00 0 
20f200000-20f204000 rw-s 00000000 00:06 463                              /dev/nvidiactl
20f204000-20f400000 ---p 00000000 00:00 0 
20f400000-20f800000 rw-s 00000000 00:06 463                              /dev/nvidiactl
20f800000-210400000 ---p 00000000 00:00 0 
210400000-210404000 rw-s 00000000 00:06 463                              /dev/nvidiactl
210404000-210600000 ---p 00000000 00:00 0 
210600000-210a00000 rw-s 00000000 00:06 463                              /dev/nvidiactl
210a00000-211600000 ---p 00000000 00:00 0 
211600000-211604000 rw-s 00000000 00:06 463                              /dev/nvidiactl
211604000-211800000 ---p 00000000 00:00 0 
211800000-211c00000 rw-s 00000000 00:06 463                              /dev/nvidiactl
211c00000-212800000 ---p 00000000 00:00 0 
212800000-212804000 rw-s 00000000 00:06 463                              /dev/nvidiactl
212804000-212a00000 ---p 00000000 00:00 0 
212a00000-212e00000 rw-s 00000000 00:06 463                              /dev/nvidiactl
212e00000-213a00000 ---p 00000000 00:00 0 
213a00000-213a04000 rw-s 00000000 00:06 463                              /dev/nvidiactl
213a04000-213c00000 ---p 00000000 00:00 0 
213c00000-214000000 rw-s 00000000 00:06 463                              /dev/nvidiactl
214000000-214c00000 ---p 00000000 00:00 0 
214c00000-214c04000 rw-s 00000000 00:06 463                              /dev/nvidiactl
214c04000-214e00000 ---p 00000000 00:00 0 
214e00000-215200000 rw-s 00000000 00:06 463                              /dev/nvidiactl
215200000-215e00000 ---p 00000000 00:00 0 
215e00000-215e04000 rw-s 00000000 00:06 463                              /dev/nvidiactl
215e04000-216000000 ---p 00000000 00:00 0 
216000000-216400000 rw-s 00000000 00:06 463                              /dev/nvidiactl
216400000-216404000 rw-s 00000000 00:06 463                              /dev/nvidiactl
216404000-216600000 ---p 00000000 00:00 0 
216600000-216a00000 rw-s 00000000 00:06 463                              /dev/nvidiactl
216a00000-216a04000 rw-s 00000000 00:06 463                              /dev/nvidiactl
216a04000-216c00000 ---p 00000000 00:00 0 
216c00000-217000000 rw-s 00000000 00:06 463                              /dev/nvidiactl
217000000-217004000 rw-s 00000000 00:06 463                              /dev/nvidiactl
217004000-217200000 ---p 00000000 00:00 0 
217200000-217600000 rw-s 00000000 00:06 463                              /dev/nvidiactl
217600000-217604000 rw-s 00000000 00:06 463                              /dev/nvidiactl
217604000-217800000 ---p 00000000 00:00 0 
217800000-217c00000 rw-s 00000000 00:06 463                              /dev/nvidiactl
217c00000-217c04000 rw-s 00000000 00:06 463                              /dev/nvidiactl
217c04000-217e00000 ---p 00000000 00:00 0 
217e00000-218200000 rw-s 00000000 00:06 463                              /dev/nvidiactl
218200000-218204000 rw-s 00000000 00:06 463                              /dev/nvidiactl
218204000-218400000 ---p 00000000 00:00 0 
218400000-218800000 rw-s 00000000 00:06 463                              /dev/nvidiactl
218800000-218804000 rw-s 00000000 00:06 463                              /dev/nvidiactl
218804000-218a00000 ---p 00000000 00:00 0 
218a00000-218e00000 rw-s 00000000 00:06 463                              /dev/nvidiactl
218e00000-219000000 ---p 00000000 00:00 0 
219000000-219200000 rw-s 00000000 00:06 463                              /dev/nvidiactl
219200000-219400000 rw-s 00000000 00:06 463                              /dev/nvidiactl
219400000-219600000 rw-s 00000000 00:06 463                              /dev/nvidiactl
219600000-219800000 ---p 00000000 00:00 0 
219800000-219804000 rw-s 00000000 00:06 463                              /dev/nvidiactl
219804000-219a00000 ---p 00000000 00:00 0 
219a00000-219e00000 rw-s 00000000 00:06 463                              /dev/nvidiactl
219e00000-21aa00000 ---p 00000000 00:00 0 
21aa00000-21aa04000 rw-s 00000000 00:06 463                              /dev/nvidiactl
21aa04000-21ac00000 ---p 00000000 00:00 0 
21ac00000-21b000000 rw-s 00000000 00:06 463                              /dev/nvidiactl
21b000000-21bc00000 ---p 00000000 00:00 0 
21bc00000-21bc04000 rw-s 00000000 00:06 463                              /dev/nvidiactl
21bc04000-21be00000 ---p 00000000 00:00 0 
21be00000-21c200000 rw-s 00000000 00:06 463                              /dev/nvidiactl
21c200000-21ce00000 ---p 00000000 00:00 0 
21ce00000-21ce04000 rw-s 00000000 00:06 463                              /dev/nvidiactl
21ce04000-21d000000 ---p 00000000 00:00 0 
21d000000-21d400000 rw-s 00000000 00:06 463                              /dev/nvidiactl
21d400000-21e000000 ---p 00000000 00:00 0 
21e000000-21e004000 rw-s 00000000 00:06 463                              /dev/nvidiactl
21e004000-21e200000 ---p 00000000 00:00 0 
21e200000-21e600000 rw-s 00000000 00:06 463                              /dev/nvidiactl
21e600000-21f200000 ---p 00000000 00:00 0 
21f200000-21f204000 rw-s 00000000 00:06 463                              /dev/nvidiactl
21f204000-21f400000 ---p 00000000 00:00 0 
21f400000-21f800000 rw-s 00000000 00:06 463                              /dev/nvidiactl
21f800000-220400000 ---p 00000000 00:00 0 
220400000-220404000 rw-s 00000000 00:06 463                              /dev/nvidiactl
220404000-220600000 ---p 00000000 00:00 0 
220600000-220a00000 rw-s 00000000 00:06 463                              /dev/nvidiactl
220a00000-221600000 ---p 00000000 00:00 0 
221600000-221604000 rw-s 00000000 00:06 463                              /dev/nvidiactl
221604000-221800000 ---p 00000000 00:00 0 
221800000-221c00000 rw-s 00000000 00:06 463                              /dev/nvidiactl
221c00000-222800000 ---p 00000000 00:00 0 
222800000-222804000 rw-s 00000000 00:06 463                              /dev/nvidiactl
222804000-222a00000 ---p 00000000 00:00 0 
222a00000-222e00000 rw-s 00000000 00:06 463                              /dev/nvidiactl
222e00000-222e04000 rw-s 00000000 00:06 463                              /dev/nvidiactl
222e04000-223000000 ---p 00000000 00:00 0 
223000000-223400000 rw-s 00000000 00:06 463                              /dev/nvidiactl
223400000-223404000 rw-s 00000000 00:06 463                              /dev/nvidiactl
223404000-223600000 ---p 00000000 00:00 0 
223600000-223a00000 rw-s 00000000 00:06 463                              /dev/nvidiactl
223a00000-223a04000 rw-s 00000000 00:06 463                              /dev/nvidiactl
223a04000-223c00000 ---p 00000000 00:00 0 
223c00000-224000000 rw-s 00000000 00:06 463                              /dev/nvidiactl
224000000-224004000 rw-s 00000000 00:06 463                              /dev/nvidiactl
224004000-224200000 ---p 00000000 00:00 0 
224200000-224600000 rw-s 00000000 00:06 463                              /dev/nvidiactl
224600000-224604000 rw-s 00000000 00:06 463                              /dev/nvidiactl
224604000-224800000 ---p 00000000 00:00 0 
224800000-224c00000 rw-s 00000000 00:06 463                              /dev/nvidiactl
224c00000-224c04000 rw-s 00000000 00:06 463                              /dev/nvidiactl
224c04000-224e00000 ---p 00000000 00:00 0 
224e00000-225200000 rw-s 00000000 00:06 463                              /dev/nvidiactl
225200000-225204000 rw-s 00000000 00:06 463                              /dev/nvidiactl
225204000-225400000 ---p 00000000 00:00 0 
225400000-225800000 rw-s 00000000 00:06 463                              /dev/nvidiactl
225800000-225a00000 ---p 00000000 00:00 0 
225a00000-225c00000 rw-s 00000000 00:06 463                              /dev/nvidiactl
225c00000-225e00000 rw-s 00000000 00:06 463                              /dev/nvidiactl
225e00000-226000000 rw-s 00000000 00:06 463                              /dev/nvidiactl
226000000-226200000 ---p 00000000 00:00 0 
226200000-226204000 rw-s 00000000 00:06 463                              /dev/nvidiactl
226204000-226400000 ---p 00000000 00:00 0 
226400000-226800000 rw-s 00000000 00:06 463                              /dev/nvidiactl
226800000-227400000 ---p 00000000 00:00 0 
227400000-227404000 rw-s 00000000 00:06 463                              /dev/nvidiactl
227404000-227600000 ---p 00000000 00:00 0 
227600000-227a00000 rw-s 00000000 00:06 463                              /dev/nvidiactl
227a00000-228600000 ---p 00000000 00:00 0 
228600000-228604000 rw-s 00000000 00:06 463                              /dev/nvidiactl
228604000-228800000 ---p 00000000 00:00 0 
228800000-228c00000 rw-s 00000000 00:06 463                              /dev/nvidiactl
228c00000-229800000 ---p 00000000 00:00 0 
229800000-229804000 rw-s 00000000 00:06 463                              /dev/nvidiactl
229804000-229a00000 ---p 00000000 00:00 0 
229a00000-229e00000 rw-s 00000000 00:06 463                              /dev/nvidiactl
229e00000-22aa00000 ---p 00000000 00:00 0 
22aa00000-22aa04000 rw-s 00000000 00:06 463                              /dev/nvidiactl
22aa04000-22ac00000 ---p 00000000 00:00 0 
22ac00000-22b000000 rw-s 00000000 00:06 463                              /dev/nvidiactl
22b000000-22bc00000 ---p 00000000 00:00 0 
22bc00000-22bc04000 rw-s 00000000 00:06 463                              /dev/nvidiactl
22bc04000-22be00000 ---p 00000000 00:00 0 
22be00000-22c200000 rw-s 00000000 00:06 463                              /dev/nvidiactl
22c200000-22ce00000 ---p 00000000 00:00 0 
22ce00000-22ce04000 rw-s 00000000 00:06 463                              /dev/nvidiactl
22ce04000-22d000000 ---p 00000000 00:00 0 
22d000000-22d400000 rw-s 00000000 00:06 463                              /dev/nvidiactl
22d400000-22e000000 ---p 00000000 00:00 0 
22e000000-22e004000 rw-s 00000000 00:06 463                              /dev/nvidiactl
22e004000-22e200000 ---p 00000000 00:00 0 
22e200000-22e600000 rw-s 00000000 00:06 463                              /dev/nvidiactl
22e600000-22f200000 ---p 00000000 00:00 0 
22f200000-22f204000 rw-s 00000000 00:06 463                              /dev/nvidiactl
22f204000-22f400000 ---p 00000000 00:00 0 
22f400000-22f800000 rw-s 00000000 00:06 463                              /dev/nvidiactl
22f800000-22f804000 rw-s 00000000 00:06 463                              /dev/nvidiactl
22f804000-22fa00000 ---p 00000000 00:00 0 
22fa00000-22fe00000 rw-s 00000000 00:06 463                              /dev/nvidiactl
22fe00000-22fe04000 rw-s 00000000 00:06 463                              /dev/nvidiactl
22fe04000-230000000 ---p 00000000 00:00 0 
230000000-230400000 rw-s 00000000 00:06 463                              /dev/nvidiactl
230400000-230404000 rw-s 00000000 00:06 463                              /dev/nvidiactl
230404000-230600000 ---p 00000000 00:00 0 
230600000-230a00000 rw-s 00000000 00:06 463                              /dev/nvidiactl
230a00000-230a04000 rw-s 00000000 00:06 463                              /dev/nvidiactl
230a04000-230c00000 ---p 00000000 00:00 0 

230c00000-231000000 rw-s 00000000 00:06 463                              /dev/nvidiactl (core dumped)

current master branch makes error more scarcely.  relative to previous version, but still throws error.
it takes 6 hours to get error above

**Comment by ftynse** [comment]
>  Check failed: !subscriptAff.get() expected one piece

This was solved by #202 and follow-ups.  Should not appear anymore.

> F0327 00:42:49.319197  9064 genetic_tuning_harness.cc:437] [CUDA][FATAL] cuda error on gpu 7: Error at: /home/ubuntu/TensorComprehensions/src/autotuner/genetic_tuning_harness.cc:435: an illegal memory access was encountered

This was not and I could not reproduce it.  Potentially related to #179 / #226, although I could not reproduce the problem even without #226.  This is a fatal error because GPU memory corruption is very hard to recover from.

**Comment by ftynse** [comment]
@seongwook-ham  would you mind opening new tickets for different issues?  It becomes increasingly hard to keep track of what the actual problem is here.

**Comment by seongwook-ham** [comment]
ok i'll

**Comment by skimo-openhub** [comment]
On Tue, Apr 10, 2018 at 02:46:46PM -0700, ftynse wrote:
> > Error in `python': free(): invalid next size (normal): 0x00007f9ccc716dd0 ***
> 
> @skimo-openhub could reproduce this AFAIK.

I ran into _some_ memory problem, but not this one.

skimo
